# Generated by Django 4.2.2 on 2023-06-12 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productos_celulares_productos_notebooks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productos_celulares',
            new_name='producto_celulare',
        ),
        migrations.RenameModel(
            old_name='productos_notebooks',
            new_name='producto_notebook',
        ),
        migrations.RenameModel(
            old_name='productos_pcs',
            new_name='producto_pc',
        ),
    ]
