# Generated by Django 4.2.2 on 2023-06-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_logo_transicione'),
    ]

    operations = [
        migrations.CreateModel(
            name='transicione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='transiciones')),
            ],
        ),
        migrations.DeleteModel(
            name='logo_transicione',
        ),
    ]
