# Generated by Django 4.2.2 on 2023-06-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_pegatina_delete_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pegatina',
        ),
    ]
